# 🚀 QUICK DEPLOYMENT FIX SCRIPT
# Run this to fix common Render deployment issues

Write-Host "🔧 Job Portal - Deployment Fix Script" -ForegroundColor Cyan
Write-Host "=====================================" -ForegroundColor Cyan

# Check if we're in the right directory
$currentDir = Get-Location
if (-not (Test-Path "render.yaml")) {
    Write-Host "❌ Error: render.yaml not found. Please run this script from the Job_Portal root directory." -ForegroundColor Red
    exit 1
}

Write-Host "✅ Found render.yaml file" -ForegroundColor Green

# Backup original render.yaml
Write-Host "📋 Creating backup of render.yaml..." -ForegroundColor Yellow
Copy-Item "render.yaml" "render.yaml.backup" -Force
Write-Host "✅ Backup created: render.yaml.backup" -ForegroundColor Green

# Check Git status
Write-Host "`n📊 Checking Git status..." -ForegroundColor Yellow
$gitStatus = git status --porcelain
if ($gitStatus) {
    Write-Host "⚠️  Uncommitted changes detected:" -ForegroundColor Yellow
    git status --short
    
    $commit = Read-Host "`nDo you want to commit these changes? (y/n)"
    if ($commit -eq "y" -or $commit -eq "Y") {
        Write-Host "📝 Adding and committing changes..." -ForegroundColor Yellow
        git add .
        git commit -m "Fix Render deployment configuration - $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
        Write-Host "✅ Changes committed" -ForegroundColor Green
    }
} else {
    Write-Host "✅ Git working directory is clean" -ForegroundColor Green
}

# Check if backend directory exists
Write-Host "`n📁 Verifying project structure..." -ForegroundColor Yellow
if (Test-Path "backend") {
    Write-Host "✅ backend/ directory found" -ForegroundColor Green
} else {
    Write-Host "❌ backend/ directory not found!" -ForegroundColor Red
    Write-Host "Please ensure your project structure is correct." -ForegroundColor Red
    exit 1
}

if (Test-Path "frontend") {
    Write-Host "✅ frontend/ directory found" -ForegroundColor Green
} else {
    Write-Host "❌ frontend/ directory not found!" -ForegroundColor Red
    exit 1
}

# Check package.json files
Write-Host "`n📦 Checking package.json files..." -ForegroundColor Yellow
if (Test-Path "backend/package.json") {
    Write-Host "✅ backend/package.json found" -ForegroundColor Green
    
    # Check start script
    $backendPkg = Get-Content "backend/package.json" | ConvertFrom-Json
    if ($backendPkg.scripts.start) {
        Write-Host "✅ Backend start script: $($backendPkg.scripts.start)" -ForegroundColor Green
    } else {
        Write-Host "⚠️  No start script found in backend/package.json" -ForegroundColor Yellow
    }
} else {
    Write-Host "❌ backend/package.json not found!" -ForegroundColor Red
}

if (Test-Path "frontend/package.json") {
    Write-Host "✅ frontend/package.json found" -ForegroundColor Green
    
    # Check build script
    $frontendPkg = Get-Content "frontend/package.json" | ConvertFrom-Json
    if ($frontendPkg.scripts.build) {
        Write-Host "✅ Frontend build script: $($frontendPkg.scripts.build)" -ForegroundColor Green
    } else {
        Write-Host "⚠️  No build script found in frontend/package.json" -ForegroundColor Yellow
    }
} else {
    Write-Host "❌ frontend/package.json not found!" -ForegroundColor Red
}

# Display render.yaml content
Write-Host "`n📄 Current render.yaml configuration:" -ForegroundColor Yellow
Write-Host "=====================================" -ForegroundColor Yellow
Get-Content "render.yaml" | Write-Host

# Environment variables check
Write-Host "`n🔑 Environment Variables Checklist:" -ForegroundColor Yellow
Write-Host "=====================================" -ForegroundColor Yellow
Write-Host "Backend environment variables to set in Render Dashboard:" -ForegroundColor Cyan
Write-Host "✓ MONGO_URI (your MongoDB Atlas connection string)" -ForegroundColor White
Write-Host "✓ CLOUDINARY_CLOUD_NAME (your Cloudinary cloud name)" -ForegroundColor White
Write-Host "✓ CLOUDINARY_API_KEY (your Cloudinary API key)" -ForegroundColor White
Write-Host "✓ CLOUDINARY_API_SECRET (your Cloudinary API secret)" -ForegroundColor White
Write-Host "✓ GEMINI_API_KEY (your Google Gemini API key)" -ForegroundColor White
Write-Host "✓ JWT_SECRET (will be auto-generated by Render)" -ForegroundColor Gray

Write-Host "`nFrontend environment variables:" -ForegroundColor Cyan
Write-Host "✓ VITE_API_URL (will be auto-populated from backend service)" -ForegroundColor White

# Next steps
Write-Host "`n🚀 NEXT STEPS:" -ForegroundColor Green
Write-Host "==============" -ForegroundColor Green
Write-Host "1. Push changes to GitHub:" -ForegroundColor Yellow
Write-Host "   git push origin main" -ForegroundColor White
Write-Host ""
Write-Host "2. Go to Render Dashboard and:" -ForegroundColor Yellow
Write-Host "   - Delete existing services (if any)" -ForegroundColor White
Write-Host "   - Click 'New' → 'Blueprint'" -ForegroundColor White
Write-Host "   - Select your GitHub repository" -ForegroundColor White
Write-Host "   - Let Render read render.yaml automatically" -ForegroundColor White
Write-Host ""
Write-Host "3. After services are created, add environment variables:" -ForegroundColor Yellow
Write-Host "   - Go to backend service → Environment tab" -ForegroundColor White
Write-Host "   - Add the variables listed above" -ForegroundColor White
Write-Host "   - Click 'Save Changes'" -ForegroundColor White
Write-Host ""
Write-Host "4. Monitor deployment in Render logs" -ForegroundColor Yellow

Write-Host "`n✅ Script completed successfully!" -ForegroundColor Green
Write-Host "If you still encounter issues, check DEPLOYMENT_TROUBLESHOOTING.md" -ForegroundColor Cyan

# Option to push to GitHub
Write-Host ""
$push = Read-Host "Do you want to push changes to GitHub now? (y/n)"
if ($push -eq "y" -or $push -eq "Y") {
    Write-Host "🚀 Pushing to GitHub..." -ForegroundColor Yellow
    git push origin main
    Write-Host "✅ Changes pushed to GitHub!" -ForegroundColor Green
    Write-Host ""
    Write-Host "🎯 Now go to Render Dashboard and deploy with Blueprint!" -ForegroundColor Cyan
    Write-Host "https://render.com" -ForegroundColor Blue
}